name: Environmenet Variables
on: [push]
env:
    WF_LEVEL_ENV: Available to all jobs

jobs: 
    env-vars-and-context:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        env:
            JOB_LEVEL_ENV: Available to all steps in this job "env-vars-and-context"
        steps:
            - name: log ENV CAR
              run: echo $GITHUB_REF}}
            - name: log Context
              run: echo '${{github.ref}}'
            - name: Log Custom ENV Vars
              env:
                  STEP_LEVEL_ENV: Available only to this step
              run: |
                  echo '${{ env.STEP_LEVEL_ENV }}'
                  echo $WF_LEVEL_ENV"
                  echo $JOB_LEVEL_ENV"
                  echo $STEP_LEVEL_ENV"