name: Repository Events
on: 
    push:
        branches: 
         - main
         #- "feature/**" #it will trigger for any feature branch
         - "!feature-branch"
        #branches-ignore:
        #- develop
        tags:
         - 'v*.*.*'
         - "!v1.1.1"   
        paths:
         - 'src/**'
         - '!docs/**'
         - '!test.txt'
          
    pull_request:
        types: [opened, assigned, synchronize, reopened]
        #branches: 
        # - main
        paths:
         - 'src/**'
         - '!docs/**'
         - '!test.txt'


    issues:
        types: [opened]

jobs:
    checkout_test:
        runs-on: ubuntu-latest
        steps:
        - run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
        - uses: actions/checkout@v3
