name: first-workflow

on: push

jobs:
  run-shell-ommands:
    runs-on: ubuntu-latest
    steps:
    - name: echo a string
      run: echo "hello world"
    - name: multiline command
      run: |
        node -v
        npm -va

  parallel-job-macos:
    runs-on: macos-latest
    steps:
    - name: View SW Version
      run: sw_vers
    

  dependant-job:
    needs: run-shell-ommands
    runs-on: windows-latest
    steps:
    - name: echo another string
      run:  write-output "Windows String"
    - name: Error Step
      run: doesnotexist
  
