#below code is for running job multiple times with matrix config functionality
# name: Matrix
# on: [push]

# jobs:
#   node-matrix:
#     continue-on-error: false
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest] #this one is for both ubuntu and windows
#         node-version: [14, 15, 16] #this one is for node versions i.e job will run 6 time each for ubuntu and windows

#       fail-fast: false
#       # max-parallel: 3
#     runs-on: ${{ matrix.os }}
#     steps:
#       - run: node -v
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: node -v



##below code i sfor including and excluding matrix configurations

name: Matrix
on: [push]

#------- ORIGINAL --------#
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 17 }

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 15
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-latest
            node-version: 14
      fail-fast: false
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v