#this helps to scehdule stale issues and PRs with cron - follow crontab.guru page for more info on cron syntax

name: Stale Issues and PRs
on:
  schedule:
    - cron: '0 15 * * *'  # Runs every 15th everyday
    - cron: '0/5 * * * *'   # Runs every 5 min for testing
jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - name: Run Stale Action
              uses: actions/stale@v6
              with:
                stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
                days-before-stale: 1
                days-before-close: 5
                exempt-issue-labels: 'pinned,important'
                exempt-pr-labels: 'pinned,important'
                only-labels: 'bug,enhancement'